<?php
/*
 * @file
 * code for Mailjet Stats submodule
*/

/*
 * Custom code for stats iframe.
  */

function mailjet_stats_iframe() {
  define("IFRAME_URL", "https://app.mailjet.com/");
  $config_mailjet = \Drupal::config('mailjet.settings');

  if (empty($config_mailjet->get('mailjet_active')) && empty($config_mailjet->get('mailjet_username')) && empty($config_mailjet->get('mailjet_password'))) {
    drupal_set_message(t('You need to add your Mailjet API details before you can continue'), 'warning');
    $response = new RedirectResponse('admin/config/mailjet/settings');
    $response->send();
  }

  $token = $config_mailjet->get('APItoken');

  if (!empty($token)) {
    global $base_url;
    global $language;

    $lang_codes_map = [
      'en' => 'en_US',
      'fr' => 'fr_FR',
      'de' => 'de_DE',
      'es' => 'es_ES',
      'it' => 'it_IT',
    ];
    $default_lang = 'en';
    $locale = isset($lang_codes_map[$language->getId()]) ? $lang_codes_map[$language->getId()] : $lang_codes_map[$default_lang];

    $callbackurl = 't=' . $token . '&show_menu=none&sp=display&u=Drupal-8.0&locale=' . $locale;

    $default_url = IFRAME_URL . "stats?";

    return $default_url . $callbackurl;
  }
  return t('Unable to generate registration form.');
}
