<?php
/*
 * @file
 * code for Mailjet List  submodule
*/


/**
 * Custom function for list Iframe.
 */
function mailjet_list_iframe() {
  $config_mailjet =\Drupal::config('mailjet.settings');

  define("IFRAME_URL", "https://app.mailjet.com/");
  if (empty($config_mailjet->get('mailjet_active')) && empty($config_mailjet->get('mailjet_username')) && empty($config_mailjet->get('mailjet_password'))) {
    drupal_set_message(t('You need to add your Mailjet API details before you can continue'), 'warning');
    $response = new RedirectResponse('admin/config/mailjet/settings');
    $response->send();
  }

  $token = $config_mailjet->get('APItoken');
  if (!empty($token)) {
    global $base_url;
    $language = \Drupal::languageManager()->getCurrentLanguage();

    $lang_codes_map = [
      'en' => 'en_US',
      'fr' => 'fr_FR',
      'de' => 'de_DE',
      'es' => 'es_ES',
      'it' => 'it_IT',
    ];

    $default_lang = 'en';
    $locale = isset($lang_codes_map[$language->getId()]) ? $lang_codes_map[$language->getId()] : $lang_codes_map[$default_lang];

    $callbackurl = 't=' . $token . '&show_menu=none&sp=display&u=Drupal-8.0&locale=' . $locale;

    $default_url = IFRAME_URL . "contacts?";

    return $default_url . $callbackurl;
  }
  return t('Unable to generate campaign.');
}

